# Generated by Django 5.2.8 on 2025-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='student_pictures/default_profile.png', null=True, upload_to='student_pictures/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='instructor_pictures/default_profile.png', null=True, upload_to='instructor_pictures/'),
        ),
    ]
