# Generated by Django 5.2.8 on 2025-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
