# Generated by Django 5.2.8 on 2025-11-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_trainer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='academy.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='images/default_course.png', null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academy.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='student_pictures/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='instructor_pictures/'),
        ),
    ]
