# Generated by Django 5.2.8 on 2025-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_trainer_courses_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainers', to='academy.course'),
        ),
    ]
