# Generated by Django 5.2.8 on 2025-11-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_trainer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.trainer'),
        ),
    ]
