# Generated by Django 5.2.8 on 2025-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_remove_course_instructor_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=8),
            preserve_default=False,
        ),
    ]
