# Generated by Django 5.2.8 on 2025-11-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
