# Generated by Django 5.2.8 on 2025-11-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_trainer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='default_course.png', null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='student_pictures/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='instructor_pictures/'),
        ),
    ]
